### ISSUE TITLE
arm 下无法加载libhpsocket4c

### ISSUE THREAD

**Issue by ahthabc** [int2e/HPSocket.Net#22]
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'hpsocket4c' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libhpsocket4c: cannot open shared object file: No such file or directory

树莓派OS

**Comment by int2e** [comment]
搞定了没有， 自己编译一份放目录下吧。。。

**Comment by int2e** [comment]
我的qq1013706666有问题可以直接联系我

**Comment by canyanol650** [comment]
我这也是这个错误

Unhandled exception. System.TypeInitializationException: The type initializer for 'HF.PositionConverter.Core.UdpHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'hpsocket4c' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libhpsocket4c: cannot open shared object file: No such file or directory

同问   以下是操作系统版本
Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

Linux version 5.10.103-v7l+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1529 SMP Tue Mar 8 12:24:00 GMT 2022

**Comment by ahthabc** [comment]
抱歉，后来没有搞了！可能是glibc的版本问题，该树莓派的系统版本中的libc.so.6 中最大到2.28，而libhpsocket4c.so  好像需要2.29版本的
